// 크리스천 묵상 팩 (church 프리셋) 공유 정의
// /diary(수채화 다이어리 제작소)와 /advanced/qt(큐티 + 묵상 팩)가
// 이 상수를 함께 사용하므로, 팩 구성을 변경하면 양쪽에 자동 반영된다.
export const CHURCH_PRESET_PAGES: Record<string, boolean> = {
  yearlygrid: true,
  calendar: true,
  overview: true,
  weekly: true,
  daily: true,
  habit: false,
  habit2: false,
  gratitude: false,
  quote: false,
  budget: false,
  budget2: false,
  culture: false,
  culture2: false,
  kpt: false,
  kpt2: false,
  sundaygeneral: false,
  buckettravel: false,
  wellnessmood: false,
  hundredgoal: false,
  hundredgoal2: false,
  prayer: true,
  prayer2: true,
  scripture: true,
  scripture2: true,
  sermon: true,
  sermondeep: true,
  biblemap: true,
  biblemap2: true,
  letter: true,
  letter2: true,
  intercessory: true,
  intercessory2: true,
  soapjournal: true,
  soapjournal2: true,
  fruitstracker: true,
  cover: true,
  monthlydivider: true,
  wallcalendar: true,
}
