export const PPT_THEME = {
  cover: {
    bg: '1a3a6b',
    accentBg: '254e8a',
    titleColor: 'FFFFFF',
    subtitleColor: 'B0C4DF',
    dateColor: '8BA4C7',
  },
  content: {
    bg: 'FFFFFF',
    titleColor: '1a3a6b',
    bodyColor: '2D3748',
    accentColor: '3182F6',
    accentLight: 'EBF4FF',
    dividerColor: 'E2E8F0',
    bulletColor: '4A5568',
  },
  toc: {
    bg: 'F0F4FA',
    titleColor: '1a3a6b',
    itemColor: '2D3748',
    accentColor: '3182F6',
  },
  scripture: {
    bg: '1a3a6b',
    titleColor: 'FFFFFF',
    bodyColor: 'E2EDFF',
    verseColor: 'F6E05E',
  },
  end: {
    bg: '1a3a6b',
    titleColor: 'FFFFFF',
    subtitleColor: 'B0C4DF',
    iconColor: 'F6E05E',
  },
  apply: {
    bg: 'F0F4FA',
    titleColor: '1a3a6b',
    bodyColor: '2D3748',
    accentColor: '3182F6',
  },
  font: {
    face: 'Noto Sans KR',
    title: 36,
    subtitle: 26,
    body: 26,
    small: 18,
    tiny: 14,
    tocTitle: 38,
    tocItem: 24,
    coverTitle: 48,
    coverSubtitle: 30,
    scriptureTitle: 28,
    scriptureBody: 24,
  },
  layout: {
    slideWidth: 10,
    slideHeight: 7.5,
    marginX: 0.6,
    marginY: 0.3,
    contentWidth: 8.8,
    centerX: 5,
    contentHeight: 5.2,
    titleHeight: 0.7,
    titleTop: 0.3,
    contentTop: 1.2,
    accentBar: 0.1,
  },
}
