export interface QtTemplate {
  id: string
  name: string
  nameEn: string
  description: string
  font: string
  fontHeading: string
  pageBg: string
  textColor: string
  textMuted: string
  accent: string
  accentLight: string
  border: string
  borderLight: string
  coverOrnament: string
  coverAccentLine: string
  sectionLabelBorder: string
  bibleQuoteBg: string
  bibleQuoteBorder: string
  bibleQuoteText: string
  prayerBoxBg: string
  prayerBoxText: string
  progressDotBg: string
  progressDotBorder: string
  progressDotActiveBg: string
  pageNumberColor: string
  coverTitleSize: string
  coverSubtitleColor: string
  bodyLineHeight: string
  bodySize: string
}

export const QT_TEMPLATES: QtTemplate[] = [
  {
    id: 'publication-2a',
    name: '클래식 출판',
    nameEn: 'Classic Editorial',
    description: '깔끔한 네이비/골드 편집 디자인, 한영 병렬 2단',
    font: "'Noto Serif KR', 'Noto Sans KR', 'Apple SD Gothic Neo', 'Malgun Gothic', serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#ffffff',
    textColor: '#1a1f2e',
    textMuted: '#5c6478',
    accent: '#1e2a47',
    accentLight: '#f4f1ea',
    border: '#d8d2c4',
    borderLight: '#ece6d7',
    coverOrnament: '— ◆ —',
    coverAccentLine: '#a08543',
    sectionLabelBorder: '#1e2a47',
    bibleQuoteBg: '#fbf9f4',
    bibleQuoteBorder: '#1e2a47',
    bibleQuoteText: '#1a1f2e',
    prayerBoxBg: '#f7f3ea',
    prayerBoxText: '#1a1f2e',
    progressDotBg: '#d8d2c4',
    progressDotBorder: '#a08543',
    progressDotActiveBg: '#1e2a47',
    pageNumberColor: '#8a7e62',
    coverTitleSize: '28px',
    coverSubtitleColor: '#a08543',
    bodyLineHeight: '1.65',
    bodySize: '11px',
  },
  {
    id: 'qtland-classic',
    name: '큐티랜드 클래식',
    nameEn: 'QTLand Classic',
    description: '정갈한 교재형 블루/민트 테마',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#ffffff',
    textColor: '#1e293b',
    textMuted: '#64748b',
    accent: '#1d4ed8',
    accentLight: '#eff6ff',
    border: '#cbd5e1',
    borderLight: '#f1f5f9',
    coverOrnament: '◇ ◇ ◇',
    coverAccentLine: '#1d4ed8',
    sectionLabelBorder: '#1d4ed8',
    bibleQuoteBg: '#f8fafc',
    bibleQuoteBorder: '#1d4ed8',
    bibleQuoteText: '#1e293b',
    prayerBoxBg: '#f0fdf4',
    prayerBoxText: '#166534',
    progressDotBg: '#e2e8f0',
    progressDotBorder: '#cbd5e1',
    progressDotActiveBg: '#1d4ed8',
    pageNumberColor: '#64748b',
    coverTitleSize: '28px',
    coverSubtitleColor: '#1d4ed8',
    bodyLineHeight: '1.6',
    bodySize: '11.5px',
  },
  {
    id: 'warm-modern',
    name: '따뜻한 모던',
    nameEn: 'Warm Modern',
    description: '세련된 인디고 테마, 전문적인 분위기',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#ffffff',
    textColor: '#1e1e2a',
    textMuted: '#475569',
    accent: '#3730a3',
    accentLight: '#eef2ff',
    border: '#cbd5e1',
    borderLight: '#f1f5f9',
    coverOrnament: '━━━',
    coverAccentLine: '#3730a3',
    sectionLabelBorder: '#3730a3',
    bibleQuoteBg: '#f8fafc',
    bibleQuoteBorder: '#3730a3',
    bibleQuoteText: '#1e1e2a',
    prayerBoxBg: '#f1f5f9',
    prayerBoxText: '#1e1e2a',
    progressDotBg: '#cbd5e1',
    progressDotBorder: '#94a3b8',
    progressDotActiveBg: '#3730a3',
    pageNumberColor: '#64748b',
    coverTitleSize: '28px',
    coverSubtitleColor: '#3730a3',
    bodyLineHeight: '1.6',
    bodySize: '12px',
  },
  {
    id: 'modern-dark',
    name: '모던 다크',
    nameEn: 'Modern Dark',
    description: '세련된 다크 테마, 디지털 친화적',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#0f172a',
    textColor: '#f8fafc',
    textMuted: '#cbd5e1',
    accent: '#a5b4fc',
    accentLight: '#1e1b4b',
    border: '#475569',
    borderLight: '#334155',
    coverOrnament: '✦ ✦ ✦',
    coverAccentLine: '#a5b4fc',
    sectionLabelBorder: '#a5b4fc',
    bibleQuoteBg: '#1e293b',
    bibleQuoteBorder: '#a5b4fc',
    bibleQuoteText: '#f8fafc',
    prayerBoxBg: '#1e293b',
    prayerBoxText: '#f8fafc',
    progressDotBg: '#475569',
    progressDotBorder: '#64748b',
    progressDotActiveBg: '#a5b4fc',
    pageNumberColor: '#94a3b8',
    coverTitleSize: '28px',
    coverSubtitleColor: '#a5b4fc',
    bodyLineHeight: '1.7',
    bodySize: '12px',
  },
  {
    id: 'soft-pastel',
    name: '차분한 파스텔',
    nameEn: 'Soft Pastel',
    description: '부드럽고 포근한 파스텔 톤, 따뜻한 감성',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#fdf2f8',
    textColor: '#1a1625',
    textMuted: '#584a58',
    accent: '#a21caf',
    accentLight: '#fdf4ff',
    border: '#e8b5d8',
    borderLight: '#fce7f3',
    coverOrnament: '· · ·',
    coverAccentLine: '#a21caf',
    sectionLabelBorder: '#a21caf',
    bibleQuoteBg: '#fff1f2',
    bibleQuoteBorder: '#a21caf',
    bibleQuoteText: '#1a1625',
    prayerBoxBg: '#fff1f2',
    prayerBoxText: '#1a1625',
    progressDotBg: '#e8b5d8',
    progressDotBorder: '#c470a8',
    progressDotActiveBg: '#a21caf',
    pageNumberColor: '#785a70',
    coverTitleSize: '26px',
    coverSubtitleColor: '#a21caf',
    bodyLineHeight: '1.6',
    bodySize: '12px',
  },
  {
    id: 'classic',
    name: '클래식 명조',
    nameEn: 'Classic Serif',
    description: '전통 교회 스타일, 골드 악센트 + 명조체',
    font: "'Noto Serif KR', 'AppleMyungjo', serif",
    fontHeading: "'Noto Sans KR', 'Apple SD Gothic Neo', sans-serif",
    pageBg: '#faf8f5',
    textColor: '#1e1e2a',
    textMuted: '#555555',
    accent: '#74540a',
    accentLight: '#f5f0e8',
    border: '#c8bc9f',
    borderLight: '#f0ebe0',
    coverOrnament: '◆ ◆ ◆',
    coverAccentLine: '#74540a',
    sectionLabelBorder: '#74540a',
    bibleQuoteBg: '#f5f0e8',
    bibleQuoteBorder: '#74540a',
    bibleQuoteText: '#1e1e2a',
    prayerBoxBg: '#f5f0e8',
    prayerBoxText: '#1e1e2a',
    progressDotBg: '#e0d8c8',
    progressDotBorder: '#a89874',
    progressDotActiveBg: '#74540a',
    pageNumberColor: '#777777',
    coverTitleSize: '26px',
    coverSubtitleColor: '#74540a',
    bodyLineHeight: '1.8',
    bodySize: '12.5px',
  },
  {
    id: 'minimal-white',
    name: '미니멀 화이트',
    nameEn: 'Minimal White',
    description: '극한의 가독성, 모던 심플, 무색감',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    pageBg: '#ffffff',
    textColor: '#111827',
    textMuted: '#4b5563',
    accent: '#111827',
    accentLight: '#f3f4f6',
    border: '#9ca3af',
    borderLight: '#e5e7eb',
    coverOrnament: '',
    coverAccentLine: '#111827',
    sectionLabelBorder: '#111827',
    bibleQuoteBg: '#f9fafb',
    bibleQuoteBorder: '#111827',
    bibleQuoteText: '#111827',
    prayerBoxBg: '#f3f4f6',
    prayerBoxText: '#111827',
    progressDotBg: '#d1d5db',
    progressDotBorder: '#9ca3af',
    progressDotActiveBg: '#111827',
    pageNumberColor: '#6b7280',
    coverTitleSize: '28px',
    coverSubtitleColor: '#111827',
    bodyLineHeight: '1.7',
    bodySize: '12px',
  },
  {
    id: 'serene-nature',
    name: '서린 네이처',
    nameEn: 'Serene Nature',
    description: '자연에서 영감 받은 세이지 그린, 편안한 가독성',
    font: "'Noto Sans KR', 'Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif",
    fontHeading: "'Noto Serif KR', 'Noto Sans KR', 'Apple SD Gothic Neo', serif",
    pageBg: '#fafaf9',
    textColor: '#1c1917',
    textMuted: '#57534e',
    accent: '#1b4332',
    accentLight: '#f0fdf4',
    border: '#a8a29e',
    borderLight: '#e7e5e4',
    coverOrnament: '🌿',
    coverAccentLine: '#1b4332',
    sectionLabelBorder: '#1b4332',
    bibleQuoteBg: '#f5f5f4',
    bibleQuoteBorder: '#1b4332',
    bibleQuoteText: '#1c1917',
    prayerBoxBg: '#f0fdf4',
    prayerBoxText: '#1c1917',
    progressDotBg: '#d6d3d1',
    progressDotBorder: '#78716c',
    progressDotActiveBg: '#1b4332',
    pageNumberColor: '#78716c',
    coverTitleSize: '28px',
    coverSubtitleColor: '#1b4332',
    bodyLineHeight: '1.7',
    bodySize: '12px',
  },
]

export function getTemplate(id: string): QtTemplate {
  return QT_TEMPLATES.find(t => t.id === id) || QT_TEMPLATES[0]
}