-- 성경 본문 테이블 (개역개정)
CREATE TABLE IF NOT EXISTS bible_texts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_name TEXT NOT NULL,
  chapter INT NOT NULL,
  verse INT NOT NULL,
  text TEXT NOT NULL,
  UNIQUE(book_name, chapter, verse)
);

-- 빠른 검색을 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_bible_book_chapter ON bible_texts(book_name, chapter);

-- 공개 읽기 허용 (RLS)
ALTER TABLE bible_texts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bible_texts_public_read" ON bible_texts FOR SELECT USING (true);
