export interface BibleBook {
  name: string
  chapters: number
  testament: 'OT' | 'NT'
}

export const BIBLE_BOOKS: BibleBook[] = [
  { name: '창세기', chapters: 50, testament: 'OT' },
  { name: '출애굽기', chapters: 40, testament: 'OT' },
  { name: '레위기', chapters: 27, testament: 'OT' },
  { name: '민수기', chapters: 36, testament: 'OT' },
  { name: '신명기', chapters: 34, testament: 'OT' },
  { name: '여호수아', chapters: 24, testament: 'OT' },
  { name: '사사기', chapters: 21, testament: 'OT' },
  { name: '룻기', chapters: 4, testament: 'OT' },
  { name: '사무엘상', chapters: 31, testament: 'OT' },
  { name: '사무엘하', chapters: 24, testament: 'OT' },
  { name: '열왕기상', chapters: 22, testament: 'OT' },
  { name: '열왕기하', chapters: 25, testament: 'OT' },
  { name: '역대상', chapters: 29, testament: 'OT' },
  { name: '역대하', chapters: 36, testament: 'OT' },
  { name: '에스라', chapters: 10, testament: 'OT' },
  { name: '느헤미야', chapters: 13, testament: 'OT' },
  { name: '에스더', chapters: 10, testament: 'OT' },
  { name: '욥기', chapters: 42, testament: 'OT' },
  { name: '시편', chapters: 150, testament: 'OT' },
  { name: '잠언', chapters: 31, testament: 'OT' },
  { name: '전도서', chapters: 12, testament: 'OT' },
  { name: '아가', chapters: 8, testament: 'OT' },
  { name: '이사야', chapters: 66, testament: 'OT' },
  { name: '예레미야', chapters: 52, testament: 'OT' },
  { name: '예레미야애가', chapters: 5, testament: 'OT' },
  { name: '에스겔', chapters: 48, testament: 'OT' },
  { name: '다니엘', chapters: 12, testament: 'OT' },
  { name: '호세아', chapters: 14, testament: 'OT' },
  { name: '요엘', chapters: 3, testament: 'OT' },
  { name: '아모스', chapters: 9, testament: 'OT' },
  { name: '오바댜', chapters: 1, testament: 'OT' },
  { name: '요나', chapters: 4, testament: 'OT' },
  { name: '미가', chapters: 7, testament: 'OT' },
  { name: '나훔', chapters: 3, testament: 'OT' },
  { name: '하박국', chapters: 3, testament: 'OT' },
  { name: '스바냐', chapters: 3, testament: 'OT' },
  { name: '학개', chapters: 2, testament: 'OT' },
  { name: '스가랴', chapters: 14, testament: 'OT' },
  { name: '말라기', chapters: 4, testament: 'OT' },
  { name: '마태복음', chapters: 28, testament: 'NT' },
  { name: '마가복음', chapters: 16, testament: 'NT' },
  { name: '누가복음', chapters: 24, testament: 'NT' },
  { name: '요한복음', chapters: 21, testament: 'NT' },
  { name: '사도행전', chapters: 28, testament: 'NT' },
  { name: '로마서', chapters: 16, testament: 'NT' },
  { name: '고린도전서', chapters: 16, testament: 'NT' },
  { name: '고린도후서', chapters: 13, testament: 'NT' },
  { name: '갈라디아서', chapters: 6, testament: 'NT' },
  { name: '에베소서', chapters: 6, testament: 'NT' },
  { name: '빌립보서', chapters: 4, testament: 'NT' },
  { name: '골로새서', chapters: 4, testament: 'NT' },
  { name: '데살로니가전서', chapters: 5, testament: 'NT' },
  { name: '데살로니가후서', chapters: 3, testament: 'NT' },
  { name: '디모데전서', chapters: 6, testament: 'NT' },
  { name: '디모데후서', chapters: 4, testament: 'NT' },
  { name: '디도서', chapters: 3, testament: 'NT' },
  { name: '빌레몬서', chapters: 1, testament: 'NT' },
  { name: '히브리서', chapters: 13, testament: 'NT' },
  { name: '야고보서', chapters: 5, testament: 'NT' },
  { name: '베드로전서', chapters: 5, testament: 'NT' },
  { name: '베드로후서', chapters: 3, testament: 'NT' },
  { name: '요한일서', chapters: 5, testament: 'NT' },
  { name: '요한이서', chapters: 1, testament: 'NT' },
  { name: '요한삼서', chapters: 1, testament: 'NT' },
  { name: '유다서', chapters: 1, testament: 'NT' },
  { name: '요한계시록', chapters: 22, testament: 'NT' },
]
